version: '3.7'

services:
  app:
    build:
      context: .
    volumes:
      - ./:/app
      - /var
  nginx:
    image: nginx:latest
    volumes:
      - ./public/:/app/public/
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8080:80
