version: '3.7'

services:
  app:
    build:
      context: .
    command: 'php-fpm'
    restart: on-failure
  nginx:
    image: nginx:latest
    volumes:
      - ./public/:/app/public/
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8080:80
  mysql:
    image: mysql:8.0.18
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: recipe-service
      MYSQL_USER: sahtivahti
      MYSQL_PASSWORD: sahtivahti
