version: '3.7'

services:
  app:
    build:
      context: .
    command: 'php-fpm'
    volumes:
      - ./:/app
      - /var
    restart: on-failure
  nginx:
    image: nginx:latest
    volumes:
      - ./public/:/app/public/
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8080:80
  mariadb:
    image: mariadb:10.4.10
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: recipe-service
      MYSQL_USER: sahtivahti
      MYSQL_PASSWORD: sahtivahti
  rabbitmq:
    image: rabbitmq:3.8.2-management-alpine
    ports:
      - 15672:15672
      - 5672:5672

