openapi: 3.0.0
info:
  title: Sahtivahti Recipe Service
  description: |
    Recipe management in Sahtivahti app
  version: 0.0.1

paths:
  /health:
    get:
      summary: Service healthcheck
      tags:
        - Common
      description: For monitoring the service health
      responses:
        '200':
          description: The healthcheck result
          content:
            application/json:
              schema:
                type: string
                example: 'OK'
  /v1/recipe:
    get:
      summary: Search recipes
      tags:
        - Recipe
      requestBody:
        description: Recipe search filters
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecipeSearchFiltersRequest'
      responses:
        200:
          description: Filtered recipe result
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RecipeListItemResponse'
    post:
      summary: Create recipe
      tags:
        - Recipe
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRecipeRequest'
      responses:
        201:
          description: The created recipe
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecipeDetailsResponse'
  /v1/recipe/{id}:
    get:
      summary: Get recipe by id
      tags:
        - Recipe
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: The recipe
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecipeDetailsResponse'
    put:
      summary: Update recipe by id
      tags:
        - Recipe
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: The updated recipe
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecipeDetailsResponse'
    delete:
      summary: Delete recipe by id
      tags:
        - Recipe
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: The deleted recipe
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecipeDetailsResponse'

  /v1/recipe/{recipeId}/hop:
    post:
      summary: Add hop to recipe
      tags:
        - Hop
      parameters:
        - in: path
          name: recipeId
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateHopRequest'
      responses:
        201:
          description: Created hop
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HopDetailsResponse'
        404:
          description: Recipe not found
        400:
          description: Invalid hop content
  /v1/recipe/{recipeId}/hop/{hopId}:
    delete:
      summary: Remove hop from recipe
      tags:
        - Hop
      parameters:
        - in: path
          name: recipeId
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Hop removed from recipe
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HopDetailsResponse'
        404:
          description: Recipe or hop not found

components:
  schemas:
    CreateRecipeRequest:
      properties:
        name:
          type: string
          required: true
        author:
          type: string
          format: email
          required: true
        userId:
          type: string
        style:
          type: string
        batchSize:
          type: number
          minimum: 0.00
    RecipeDetailsResponse:
      properties:
        id:
          type: integer
        name:
          type: string
          required: true
        author:
          type: string
          format: email
          required: true
        userId:
          type: string
        style:
          type: string
        batchSize:
          type: number
          minimum: 0.00
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        hops:
          type: array
          items:
            $ref: '#/components/schemas/HopDetailsResponse'
    RecipeListItemResponse:
      properties:
        id:
          type: integer
        name:
          type: string
        style:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    RecipeSearchFiltersRequest:
      properties:
        name:
          type: string
        author:
          type: string
          format: email
        userId:
          type: string
        page:
          type: integer
    CreateHopRequest:
      properties:
        name:
          type: string
        quantity:
          type: number
    HopDetailsResponse:
      properties:
        id:
          type: integer
        name:
          type: string
        quantity:
          type: number
