openapi: 3.0.0
info:
  title: Sahtivahti Recipe Service
  description: |
    Recipe management in Sahtivahti app
  version: 0.0.1
paths:
  /health:
    get:
      summary: Service healthcheck
      description: For monitoring the service health
      responses:
        '200':
          content:
            application/json:
              schema:
                type: string
                example: 'OK'
  /v1/recipe:
    get:
      summary: List all recipes
      responses:
        200:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Recipe'

components:
  schemas:
    Recipe:
      properties:
        id:
          type: integer
        name:
          type: string
        author:
          type: string
          format: email
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
