name: CI

on: [ push ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Composer install
        uses: docker://composer:1.9.1
        with:
          args: install

  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: sahtivahti/recipe-service
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Composer install
        uses: docker://composer:1.9.1
        with:
          args: install
      - name: PHPStan
        uses: docker://mickaelandrieu/phpqa-ga
        with:
          args: --report --ignoredDirs vendor,Migrations --analyzedDirs src/ --output=cli --tools phpstan:0
      - name: PHP Mess Detector
        uses: docker://mickaelandrieu/phpqa-ga
        with:
          args: --report --ignoredDirs vendor,Migrations --analyzedDirs src/ --output=cli --tools phpmd:0
      - name: PHP Code Sniffer
        uses: docker://mickaelandrieu/phpqa-ga
        with:
          args: --report --ignoredDirs vendor,Migrations --analyzedDirs src/ --output=cli --tools phpcs:0
