name: CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: sahtivahti/recipe-service
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup stack
        run: docker-compose up -d
      - name: Wait until healthy
        run: while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:8080/health)" != "200" ]]; do sleep 5; done
      - name: Run behat tests
        run: docker exec recipe-service_app_1 php /app/vendor/bin/behat
      #- name: Run test
      #  run: docker run --rm --entrypoint=/usr/local/bin/php sahtivahti/recipe-service:test /app/bin/phpunit
