name: CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: sahtivahti/recipe-service
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup container
        run: docker build -t sahtivahti/recipe-service:test .
      - name: Run test
        run: docker run --rm --entrypoint=/bin/sh sahtivahti/recipe-service:test php /app/bin/phpunit
