name: CI

on: [ push ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mysql:8.0.18
        ports:
          - 3306
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: recipe-service
          MYSQL_USER: sahtivahti
          MYSQL_PASSWORD: sahtivahti
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install PHP extensions
        uses: shivammathur/setup-php@v1
        with:
          php-version: 7.4
          coverage: xdebug
          extension-csv: pdo_mysql, mbstring, json, ctype, iconv
      - name: Install Composer packages
        run: composer install
      - name: Fix permissions
        run: chmod +x ./bin/phpunit ./bin/console
      - name: Run database migrations
        run: ./bin/console doctrine:migrations:migrate --no-interaction
      - name: Run PHPUnit
        run: ./bin/phpunit --coverage-clover=coverage.xml
      - name: Report Codecov.io
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bash <(curl -s https://codecov.io/bash) || true

  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Composer install
        uses: docker://composer:1.9.1
        with:
          args: install
      - name: PHPStan
        uses: docker://mickaelandrieu/phpqa-ga
        with:
          args: --report --ignoredDirs vendor,Migrations --analyzedDirs src/ --output=cli --tools phpstan
      - name: PHP Mess Detector
        uses: docker://mickaelandrieu/phpqa-ga
        with:
          args: --report --ignoredDirs vendor,Migrations --analyzedDirs src/ --output=cli --tools phpmd:0
      - name: PHP Code Sniffer
        uses: docker://mickaelandrieu/phpqa-ga
        with:
          args: --report --ignoredDirs vendor,Migrations --analyzedDirs src/ --output=cli --tools phpcs:0

  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: sahtivahti/recipe-service
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
